/* { "x": -Math.PI, "y": 0, "z": Math.PI, },
{ "x": Math.PI, "y": 0, "z": 0 },
{ "x": -Math.PI, "y": 0, "z": Math.PI },
{ "x": 0, "y": 0, "z": 0 },
{ "x": 0, "y": 0, "z": Math.PI },
{ "x": 0, "y": 0, "z": 0 },
{ "x": -Math.PI, "y": 0, "z": Math.PI },
{ "x": Math.PI, "y": 0, "z": 0 },
{ "x": -Math.PI, "y": 0, "z": Math.PI },
{ "x": 0, "y": 0, "z": Math.PI },
{ "x": 0, "y": 0, "z": 0 },
{ "x": 0, "y": 0, "z": Math.PI },
{ "x": -Math.PI, "y": 0, "z": 0 },
{ "x": Math.PI, "y": 0, "z": Math.PI },
{ "x": Math.PI, "y": 0, "z": 0 },
{ "x": 0, "y": 0, "z": Math.PI },
{ "x": 0, "y": 0, "z": 0 },
{ "x": 0, "y": 0, "z": Math.PI },
{ "x": Math.PI, "y": 0, "z": Math.PI },
{ "x": -Math.PI, "y": 0, "z": 0 },
{ "x": Math.PI, "y": 0, "z": Math.PI },
{ "x": 0, "y": 0, "z": 0 },
{ "x": 0, "y": 0, "z": Math.PI },
{ "x": 0, "y": 0, "z": 0 },
{ "x": Math.PI, "y": 0, "z": Math.PI },
{ "x": -Math.PI, "y": 0, "z": 0 },
{ "x": Math.PI, "y": 0, "z": Math.PI } */